### ISSUE TITLE
Design frame layout

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-web-ui#1]
Use MUI open-source templates to define basic page components:

- Header
- Side bar
- Footer

**Comment by Aankirz** [comment]
I want to work on this issue can you pls assign this to me

**Comment by kartikvirendrar** [comment]
I am interested to work on this issue, should I raise a PR after designing the frame layout

**Comment by kartikvirendrar** [comment]
can we also use tailwindcss @generall

**Comment by ankitmalik84** [comment]
I want to work on this issue can you pls assign this to me

**Comment by KousikRoy-EC** [comment]
Hey can i work on this isssue?
