### ISSUE TITLE
[bug] Snapshot downloading is missing api key

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant-web-ui#106]
Very similar to <https://github.com/qdrant/qdrant-web-ui/issues/104>, but for the download endpoint.

Discord thread link: https://discord.com/channels/907569970500743200/1143482730009612318

**Comment by timvisee** [comment]
@trean Maybe you can pick this up? :smiley:

**Comment by trean** [comment]
@timvisee Fix merged and will be rolled out with the next release
