### ISSUE TITLE
there really should be a button "send" over here at the dasboard

### ISSUE THREAD

**Issue by janfilips** [qdrant/qdrant-web-ui#114]
https://drive.google.com/file/d/12ZcOreTsS8m4Oay4GSSG0oGDf_Qp8FsP/view?usp=sharing

**Comment by generall** [comment]
There is a `RUN` button next to the query. Also, you don't have any data to vizualize

**Comment by janfilips** [comment]
Got it.  Btw, the DB is currently empty, it's a development server.

Thanks for the reply.
