### ISSUE TITLE
Visualization Unsuccessful, error

### ISSUE THREAD

**Issue by samedovzaur** [qdrant/qdrant-web-ui#127]
Hi! I'm getting this error, while visualizing my dataset on dashboard. Everything raedy but the visualization doesn't work out
![Screenshot 2023-11-12 at 07 18 07](https://github.com/qdrant/qdrant-web-ui/assets/101812544/7aac2e4d-6836-4ca2-8530-83a6c3fada46)

**Comment by samedovzaur** [comment]
What should I do?

**Comment by generall** [comment]
Do you have `source` field in your payload?

**Comment by samedovzaur** [comment]
Thank you sir, solved worked on it now tryna creat my own visualization dash board, inspired by qdrant and graph knowledge visualization.

**Comment by generall** [comment]
>  tryna creat my own visualization dash board, inspired by qdrant and graph knowledge visualization.

Cool! Good luck with that!
