### ISSUE TITLE
[Console] Allow comments

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-web-ui#13]
Make commentaries (lines, starting with `//`) a valid syntax construction in console

Advanced: make any text after `//` commentary, not only the whole line

**Comment by kartik-gupta-ij** [comment]
That is already there if I am not wrong

**Comment by generall** [comment]
![Screenshot from 2023-03-26 12-54-41](https://user-images.githubusercontent.com/1935623/227773316-5e4ece9b-7e7a-4aa4-88d2-fc806ea0ce55.png)

**Comment by kartik-gupta-ij** [comment]
[Console] Allow comments #13 #15
