### ISSUE TITLE
Add vector name auto-complete in visualisation

### ISSUE THREAD

**Issue by joein** [qdrant/qdrant-web-ui#145]
The visualisation tool requires a vector name to build a map

A user does not necessarily remembers vector names, they might be bulky or they can be autogenerated (e.g. with fastembed)

To find a vector name, one need to do some extra actions, like visiting other pages or making requests to the DB.

It would be nice to have autocomplete for `vector_name` field, or have available vector names somewhere in the vicinity.

If there is only one vector in a collection, then it might also be helpful to fill `vector_name` automatically.

![image](https://github.com/qdrant/qdrant-web-ui/assets/22641570/7667aa00-2ee8-4da2-933c-707250fb9bf9)

**Comment by harshalmittal4** [comment]
Hello @joein ,
if this is unpicked I'd like to give it a try.. Thanks

**Comment by joein** [comment]
I think it has not been picked yet

I am not that up-to-date with web-ui issues, maybe @kartik-gupta-ij  could shed some light?

**Comment by kartik-gupta-ij** [comment]
> Hello @joein , if this is unpicked I'd like to give it a try.. Thanks

Assigning to you!

**Comment by harshalmittal4** [comment]
@kartik-gupta-ij Thanks!

**Comment by KShivendu** [comment]
@kartik-gupta-ij would be great if we can pick up this. 

Also, the code written in viz page should persist. It goes away if I switch to a different page which is frustrating.
