### ISSUE TITLE
Move to Vite or Next with TypeScript

### ISSUE THREAD

**Issue by nawed2611** [qdrant/qdrant-web-ui#16]
I would like to suggest moving to [Next.js](https://nextjs.org/) or [Vite](https://vitejs.dev/) with TypeScript as CRA (create-react-app) is not recommended anymore.

Below are few reasons for the same - 
1. Faster build times
2. Hot Code Reloading with Vite while Next.js provides a simplified API for handling server-side rendering and static site generation
3. Built-in TypeScript support - As the project grows, it would be helpful to have type safety within the app and the ability to access features like autocomplete through TypeScript

**Comment by nawed2611** [comment]
I would love to work on this.

**Comment by generall** [comment]
Why would we need server-side rendering for this project, while we won't have server?

Regaring Vite - I never worked with it, might be worth trying

**Comment by nawed2611** [comment]
> Why would we need server-side rendering for this project, while we won't have server?
> 
> Regaring Vite - I never worked with it, might be worth trying

Next.js provides its own server to manage SSR and is built on top of React, providing features that would be useful for this project.

**Comment by generall** [comment]
> Next.js provides its own server to manage SSR and is built on top of React,

We don't need another server, it won't work for this use-case
