### ISSUE TITLE
Point filtering by key:value pair does not work for payload fields that contain a colon ":" character

### ISSUE THREAD

**Issue by fschuh** [qdrant/qdrant-web-ui#218]
I have a payload field for a Windows file path that happen to have a colon character in it (needed for the drive name).  
For example: 
```json
{
   "file_path": "C:\folder\file.txt",
   "contents": "file contents"
}
```

Unfortunately, it seems the WebUI is too strict about its `key:value` filter format validation and won't accept colon characters on the file path.  
If I wanted to add a filter for that specific file path, this is what I would type in the search box:
`file_path: "C:\folder\file.txt"`  

When I press enter, I get the following error:
`Invalid format of key:value pair`

I also tried escaping the characters, and removing the quotes, to no avail.  

It works fine with fields that don't have a colon character.

**Comment by generall** [comment]
Thanks!
