### ISSUE TITLE
need a docker image for every release

### ISSUE THREAD

**Issue by sheikalthaf** [qdrant/qdrant-web-ui#22]
I'm currently using Qdrant and I tried it for the first time the UI and I know it is currently working in progress, 

But it is better we have a docker image for this so that we can add it to kubernetees.

Thanks

**Comment by generall** [comment]
The plan is to serve this UI from qdrant itself, so you won't need a separate docker image

**Comment by alii** [comment]
Do you think it's feasible to have a Docker image in the meantime? Would be cool to include this in my compose file while testing things out locally, without having to clone and install deps, etc

**Comment by XHHzZz** [comment]
I also feel the need for a docker image that can be configured with different addresses

**Comment by tejasvinityagi** [comment]
Hello everyone, I will create a docker image for UI component of the project

**Comment by jsimao71** [comment]
@tejasvinityagi  docker image location=?!

**Comment by kartik-gupta-ij** [comment]
Web UI is now part of the Qdrant, no docker required
