### ISSUE TITLE
[Feat]: Create a Docker Image

### ISSUE THREAD

**Issue by mahyarmirrashed** [qdrant/qdrant-web-ui#249]
We should have a Docker image for this repository. It would be much more convenient than having to clone this repository. I can make this addition so long as someone from the team can supply the secrets into the repo similar to what's happening here:

https://github.com/qdrant/qdrant/blob/master/.github/workflows/docker-image.yml

**Comment by timvisee** [comment]
At this time we do not support hosting the web UI separately. Because it's currently required to serve the web UI through Qdrant itself it does not make much sense to release a separate Docker image for it.

**Comment by mahyarmirrashed** [comment]
I'd maybe make a bit more obvious then that it's available at `localhost:6333/dashboard` on DockerHub: https://hub.docker.com/r/qdrant/qdrant
It's not immediately obvious that it is required. I think that this addition should be made because it's likely one of the first thing a practitioner of your wonderful software would want.

**Comment by mahyarmirrashed** [comment]
I'm marking it as completed, since there's nothing to be done on this repository, given your comment. I'd just suggest continue with improving the page on DockerHub.
