### ISSUE TITLE
qdrant-web-ui   console

### ISSUE THREAD

**Issue by jurchensssl** [qdrant/qdrant-web-ui#56]
What are the main functions of the web ui console? I tried using this to create collections and save the code, but it doesn't seem like I actually created it. Thank you
![image](https://github.com/qdrant/qdrant-web-ui/assets/136416211/99097227-23b3-4674-9832-1066fd9d9e1e)

**Comment by timvisee** [comment]
It is an interactive console to your Qdrant instance!

To run a snippet, click the `RUN` hint above it. I believe you can also use CTRL+Enter.

**Comment by jurchensssl** [comment]
thank you





  	
 石树礼 
厦门同步网络有限公司  
 ***@***.*** 
	     
	   		 厦门同步网络有限公司  	 企业主页  		      
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
 This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
发件人：Tim ***@***.***>
日　期：2023年06月13日 15:15:32
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [qdrant/qdrant-web-ui] qdrant-web-ui console (Issue #56)

It is an interactive console to your Qdrant instance!
To run a snippet, click the RUN hint above it. I believe you can also use CTRL+Enter.
