### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arestifo** [qdrant/qdrant-web-ui#57]
This will [reduce ambiguity](https://choosealicense.com/no-permission/) and provide ease-of-mind for companies and developers that want to use/improve this tool.

The Qdrant DB uses Apache 2.0, maybe keep going with that?

**Comment by timvisee** [comment]
Thanks for pointing this out. I've suggested this license in a PR here: https://github.com/qdrant/qdrant-web-ui/pull/58
