### ISSUE TITLE
Could you provide a dockerfile for this project?

### ISSUE THREAD

**Issue by rxy1212** [qdrant/qdrant-web-ui#62]
I build a dockerfile by myself looks below:
```
FROM node:18-alpine

WORKDIR /app

COPY . .

CMD ["npm", "start"]
```
And when I start the container, I got a error "sh: vite: not found". I'm not very familiar with front-end projects. It will make my life easier if you can provide a dockerfile which can handle all the dependencies. 
Thank you.

**Comment by generall** [comment]
Web UI is now part of the Qdrant, no docker required
