### ISSUE TITLE
Fold button hitbox is not accurate

### ISSUE THREAD

**Issue by lpi-tn** [qdrant/qdrant-web-ui#64]
Hi !
It seems the fold button on the monaco editor is not fully accurate. I need to click upper than the button I see if I want to fold my JSON.

[Capture vidéo du 26-06-2023 15:01:05.webm](https://github.com/qdrant/qdrant-web-ui/assets/133012334/dd10fbfc-480c-405a-b9ae-6d0ef60c9eaa)

**Comment by kartik-gupta-ij** [comment]
Fixed in #63
