### ISSUE TITLE
Is axios necessary?

### ISSUE THREAD

**Issue by Rendez** [qdrant/qdrant-web-ui#65]
We have the one file issuing requests other than the API itself https://github.com/qdrant/qdrant-web-ui/blob/5444af009a0d174bb1f2cc89049d51152ecbdd1b/src/components/CodeEditorWindow/config/RequesFromCode.js#L4, what's the benefit of using `axios` and thus loading more KBs on user's browsers when the same could be done with `window.fetch()`?

**Comment by Programmer-Dost** [comment]
Axios has much more functionalities and it is scalable.
