### ISSUE TITLE
Link previews render quirky

### ISSUE THREAD

**Issue by elbart** [qdrant/qdrant-web-ui#66]
See, how the link previews are rendered right now.

**Slack**: 
<img width="270" alt="Screenshot 2023-06-28 at 22 19 44" src="https://github.com/qdrant/qdrant-web-ui/assets/48974/ebc275ff-b0db-4271-85c4-36404c1963c0">
**Discord**: 
<img width="769" alt="Screenshot 2023-06-28 at 22 19 58" src="https://github.com/qdrant/qdrant-web-ui/assets/48974/ab81d281-25dc-4b98-9aba-84544be63a9b">

This looks quite ugly, so let's change this

I suggest the following changes:
**index.html**

- [x] change the `<title>` to: `UI | Qdrant` like you do already for when the SPA loads
- [x]  change the `<meta name="description">` value to: `Qdrant Web UI`

**public/manifest.json**
- [x] `short_name: "UI | Qdrant"`
- [x] `name: "Qdrant Web UI"`

**logos**
- [x] the logo being rendered in slack is either the `logo192.png` or `logo512.png`. Those need to be replaced by a qdrant logo of that size.

**Comment by Programmer-Dost** [comment]
Why this issue is still active when everything got resolved?
