### ISSUE TITLE
[Console] Autocomplete

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-web-ui#9]
Implement autocomplete for requests based on OpenAPI schema of qdrant: https://qdrant.github.io/qdrant/redoc/index.html

Autocomplete should suggest:

- next allowed work in API url. Examples
  -  `/collect` -> `["collections"]`
  - `/collections/mycollection/` -> `["points", "snapshots"]`

- Allowed fields in JSON:

```
{
  "filter": {
    "|
  }
}
```
should suggest 
```
must
should
must_not
```

**Comment by kartik-gupta-ij** [comment]
#50
